apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: laravel-app
  labels:
    app: laravel
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: app-files
          mountPath: /var/www
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p /var/log/nginx;
            chown -R www-data:www-data /var/log/nginx;
            chown -R www-data:www-data /var/www;
            nginx -t;
            nginx -g "daemon off;"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      - name: laravel
        image: laravel-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: app-files
          mountPath: /var/www
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
          - name: APP_NAME
            value: "Laravel"
          - name: APP_ENV
            value: "production"
          - name: APP_DEBUG
            value: "false"
          - name: DB_CONNECTION
            value: "mysql"
          - name: DB_HOST
            value: "mysql-service"
          - name: DB_PORT
            value: "3306"
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: default.conf
            path: default.conf
      - name: app-files
        emptyDir: {}
