apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/MTermMohamed230105474/WebSecService.git
  username: MTermMohamed230105474
  password: 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
