apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Mohamed-Hesham90/MTermMohamed_230105474.git
  username: Mohamed-Hesham90
  password: ""  # Token will be added via kubectl
