apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: laravel-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9000
      nodePort: 30080
  selector:
    app: laravel
