apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: NodePort
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      nodePort: 30080




